steps:
  # Docker Image Build
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/node-crypto-alarm-service/node-app",
          "--build-arg", "CRYPTO_API_URL=${_CRYPTO_API_URL}", "--build-arg", "FIREBASE_CREDENTIALS=${_FIREBASE_CREDENTIALS}",
          "--build-arg", "JWT_SECRET=${_JWT_SECRET}", "--build-arg", "KAFKA_BROKER=${_KAFKA_BROKER}",
          "--build-arg", "KAFKA_TOPIC=${_KAFKA_TOPIC}", "--build-arg", "MONGODB_URI=${_MONGODB_URI}",
          "--build-arg", "REDIS_URL=${_REDIS_URL}",
          "."]

  # Docker Image Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/node-crypto-alarm-service/node-app"]

  # GKE Kubernetes Cluster authorization 
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "container"
      - "clusters"
      - "get-credentials"
      - "autopilot-cluster-1"
      - "--region"
      - "us-central1"

  # Kubernetes Deployment Update
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "deployment.yaml"]
    env:
      - "CLOUDSDK_COMPUTE_REGION=us-central1"
      - "CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1"
  
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["rollout", "restart", "deployment/node-app"]
    env:
      - "CLOUDSDK_COMPUTE_REGION=us-central1"
      - "CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1"

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET