FROM node:18-alpine

WORKDIR /app

ARG JWT_SECRET
ENV JWT_SECRET ${JWT_SECRET}
ARG KAFKA_BROKER
ENV KAFKA_BROKER ${KAFKA_BROKER}
ARG KAFKA_TOPIC
ENV KAFKA_TOPIC ${KAFKA_TOPIC}
ARG MONGODB_URI
ENV MONGODB_URI ${MONGODB_URI}
ARG REDIS_URL
ENV REDIS_URL ${REDIS_URL}
ARG FIREBASE_CREDENTIALS
ENV FIREBASE_CREDENTIALS ${FIREBASE_CREDENTIALS}
ARG CRYPTO_API_URL
ENV CRYPTO_API_URL ${CRYPTO_API_URL}

# Install packages
COPY package*.json ./
RUN npm install --production

# Copy project folders
COPY . .

# Next.js build for prod 
RUN npm run build

# Execute on the prod environment
CMD ["npm", "run", "start"]
